export const SET_ROLE='SET_ROLE';
export const GET_ROLE='GET_ROLE';
export const SET_DEMOGRAPHIC_INFORMATION='SET_DEMOGRAPHIC_INFORMATION';
export const SET_OBSERVER_DEMOGRAPHIC_INFORMATION='SET_OBSERVER_DEMOGRAPHIC_INFORMATION';
export const SET_NUMBER_OF_PEOPLE_INVOLVED='SET_NUMBER_OF_PEOPLE_INVOLVED';
export const SET_INVOLVED_PEOPLE_INFORMATION='SET_INVOLVED_PEOPLE_INFORMATION';